server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5432/teamtime
spring.datasource.username=teamtime
spring.datasource.password=teamtime123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=buraya_en_az_32_karakterlik_gizli_bir_anahtar
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

verification.code.secret=${VERIFICATION_CODE_SECRET:}
