server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5432/teamtime
spring.datasource.username=teamtime
spring.datasource.password=teamtime123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=buraya_en_az_32_karakterlik_gizli_bir_anahtar
jwt.expiration=86400000
